trigger: 
- main

stages:
- stage: build
  pool: 
   vmImage: 'ubuntu-latest'
  jobs:
  - job: build_job
    steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: |
            app-backend/ECommerce.Service/ECommerce.Product.Service/ECommerce.Product.Service.csproj 




